version: '2'

volumes:
  logs:
    driver: local

services:
  demo_initial:
    image: avsej/php-couchbase-base
    command: php71 -S 0.0.0.0:8080 -t public public/index.php
    working_dir: /var/www
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
