import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nraboy' at '9/11/17 2:18 PM' with Gradle 2.4
 *
 * @author nraboy, @date 9/11/17 2:18 PM
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
